# Generated by Django 4.2.1 on 2023-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_polo", "0002_order_amount_order_color_order_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
