# Generated by Django 4.2.1 on 2023-05-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_polo", "0002_color_size_remove_product_colors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
