# Generated by Django 4.2.1 on 2023-05-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_polo", "0003_alter_product_image_alter_product_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.URLField(),
        ),
    ]
